/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermosECondicoesRouteImport } from './routes/termos-e-condicoes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ColeccaoRouteImport } from './routes/coleccao'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as ArquivoRouteImport } from './routes/arquivo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as FeedbackIdRouteImport } from './routes/feedback.$id'
import { Route as EncomendaConfirmadaOrderIdRouteImport } from './routes/encomenda-confirmada.$orderId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminReservasRouteImport } from './routes/admin_.reservas'
import { Route as AdminRelatoriosRouteImport } from './routes/admin_.relatorios'
import { Route as AdminPromocoesRouteImport } from './routes/admin_.promocoes'
import { Route as AdminProdutosRouteImport } from './routes/admin_.produtos'
import { Route as AdminEncomendasRouteImport } from './routes/admin_.encomendas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin_.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin_.clientes'
import { Route as ApiPublicHooksSendFollowupsRouteImport } from './routes/api/public/hooks/send-followups'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosECondicoesRoute = TermosECondicoesRouteImport.update({
  id: '/termos-e-condicoes',
  path: '/termos-e-condicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccaoRoute = ColeccaoRouteImport.update({
  id: '/coleccao',
  path: '/coleccao',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivoRoute = ArquivoRouteImport.update({
  id: '/arquivo',
  path: '/arquivo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIdRoute = FeedbackIdRouteImport.update({
  id: '/feedback/$id',
  path: '/feedback/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EncomendaConfirmadaOrderIdRoute =
  EncomendaConfirmadaOrderIdRouteImport.update({
    id: '/encomenda-confirmada/$orderId',
    path: '/encomenda-confirmada/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/admin_/reservas',
  path: '/admin/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin_/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromocoesRoute = AdminPromocoesRouteImport.update({
  id: '/admin_/promocoes',
  path: '/admin/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin_/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEncomendasRoute = AdminEncomendasRouteImport.update({
  id: '/admin_/encomendas',
  path: '/admin/encomendas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin_/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin_/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendFollowupsRoute =
  ApiPublicHooksSendFollowupsRouteImport.update({
    id: '/api/public/hooks/send-followups',
    path: '/api/public/hooks/send-followups',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arquivo': typeof ArquivoRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/coleccao': typeof ColeccaoRoute
  '/contactos': typeof ContactosRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quiz': typeof QuizRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/wishlist': typeof WishlistRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/encomendas': typeof AdminEncomendasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/encomenda-confirmada/$orderId': typeof EncomendaConfirmadaOrderIdRoute
  '/feedback/$id': typeof FeedbackIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/hooks/send-followups': typeof ApiPublicHooksSendFollowupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arquivo': typeof ArquivoRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/coleccao': typeof ColeccaoRoute
  '/contactos': typeof ContactosRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quiz': typeof QuizRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/wishlist': typeof WishlistRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/encomendas': typeof AdminEncomendasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/encomenda-confirmada/$orderId': typeof EncomendaConfirmadaOrderIdRoute
  '/feedback/$id': typeof FeedbackIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/hooks/send-followups': typeof ApiPublicHooksSendFollowupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arquivo': typeof ArquivoRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/coleccao': typeof ColeccaoRoute
  '/contactos': typeof ContactosRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quiz': typeof QuizRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/wishlist': typeof WishlistRoute
  '/admin_/clientes': typeof AdminClientesRoute
  '/admin_/configuracoes': typeof AdminConfiguracoesRoute
  '/admin_/encomendas': typeof AdminEncomendasRoute
  '/admin_/produtos': typeof AdminProdutosRoute
  '/admin_/promocoes': typeof AdminPromocoesRoute
  '/admin_/relatorios': typeof AdminRelatoriosRoute
  '/admin_/reservas': typeof AdminReservasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/encomenda-confirmada/$orderId': typeof EncomendaConfirmadaOrderIdRoute
  '/feedback/$id': typeof FeedbackIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/hooks/send-followups': typeof ApiPublicHooksSendFollowupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arquivo'
    | '/carrinho'
    | '/checkout'
    | '/coleccao'
    | '/contactos'
    | '/experiencias'
    | '/login'
    | '/perfil'
    | '/politica-de-privacidade'
    | '/quiz'
    | '/registo'
    | '/reset-password'
    | '/termos-e-condicoes'
    | '/wishlist'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/encomendas'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/admin/relatorios'
    | '/admin/reservas'
    | '/auth/callback'
    | '/encomenda-confirmada/$orderId'
    | '/feedback/$id'
    | '/produto/$id'
    | '/api/public/hooks/send-followups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arquivo'
    | '/carrinho'
    | '/checkout'
    | '/coleccao'
    | '/contactos'
    | '/experiencias'
    | '/login'
    | '/perfil'
    | '/politica-de-privacidade'
    | '/quiz'
    | '/registo'
    | '/reset-password'
    | '/termos-e-condicoes'
    | '/wishlist'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/encomendas'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/admin/relatorios'
    | '/admin/reservas'
    | '/auth/callback'
    | '/encomenda-confirmada/$orderId'
    | '/feedback/$id'
    | '/produto/$id'
    | '/api/public/hooks/send-followups'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arquivo'
    | '/carrinho'
    | '/checkout'
    | '/coleccao'
    | '/contactos'
    | '/experiencias'
    | '/login'
    | '/perfil'
    | '/politica-de-privacidade'
    | '/quiz'
    | '/registo'
    | '/reset-password'
    | '/termos-e-condicoes'
    | '/wishlist'
    | '/admin_/clientes'
    | '/admin_/configuracoes'
    | '/admin_/encomendas'
    | '/admin_/produtos'
    | '/admin_/promocoes'
    | '/admin_/relatorios'
    | '/admin_/reservas'
    | '/auth/callback'
    | '/encomenda-confirmada/$orderId'
    | '/feedback/$id'
    | '/produto/$id'
    | '/api/public/hooks/send-followups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArquivoRoute: typeof ArquivoRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ColeccaoRoute: typeof ColeccaoRoute
  ContactosRoute: typeof ContactosRoute
  ExperienciasRoute: typeof ExperienciasRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  QuizRoute: typeof QuizRoute
  RegistoRoute: typeof RegistoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosECondicoesRoute: typeof TermosECondicoesRoute
  WishlistRoute: typeof WishlistRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEncomendasRoute: typeof AdminEncomendasRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminPromocoesRoute: typeof AdminPromocoesRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EncomendaConfirmadaOrderIdRoute: typeof EncomendaConfirmadaOrderIdRoute
  FeedbackIdRoute: typeof FeedbackIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ApiPublicHooksSendFollowupsRoute: typeof ApiPublicHooksSendFollowupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-e-condicoes': {
      id: '/termos-e-condicoes'
      path: '/termos-e-condicoes'
      fullPath: '/termos-e-condicoes'
      preLoaderRoute: typeof TermosECondicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccao': {
      id: '/coleccao'
      path: '/coleccao'
      fullPath: '/coleccao'
      preLoaderRoute: typeof ColeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivo': {
      id: '/arquivo'
      path: '/arquivo'
      fullPath: '/arquivo'
      preLoaderRoute: typeof ArquivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$id': {
      id: '/feedback/$id'
      path: '/feedback/$id'
      fullPath: '/feedback/$id'
      preLoaderRoute: typeof FeedbackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encomenda-confirmada/$orderId': {
      id: '/encomenda-confirmada/$orderId'
      path: '/encomenda-confirmada/$orderId'
      fullPath: '/encomenda-confirmada/$orderId'
      preLoaderRoute: typeof EncomendaConfirmadaOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reservas': {
      id: '/admin_/reservas'
      path: '/admin/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/relatorios': {
      id: '/admin_/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/promocoes': {
      id: '/admin_/promocoes'
      path: '/admin/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AdminPromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/produtos': {
      id: '/admin_/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/encomendas': {
      id: '/admin_/encomendas'
      path: '/admin/encomendas'
      fullPath: '/admin/encomendas'
      preLoaderRoute: typeof AdminEncomendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/configuracoes': {
      id: '/admin_/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/clientes': {
      id: '/admin_/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-followups': {
      id: '/api/public/hooks/send-followups'
      path: '/api/public/hooks/send-followups'
      fullPath: '/api/public/hooks/send-followups'
      preLoaderRoute: typeof ApiPublicHooksSendFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArquivoRoute: ArquivoRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ColeccaoRoute: ColeccaoRoute,
  ContactosRoute: ContactosRoute,
  ExperienciasRoute: ExperienciasRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  QuizRoute: QuizRoute,
  RegistoRoute: RegistoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosECondicoesRoute: TermosECondicoesRoute,
  WishlistRoute: WishlistRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEncomendasRoute: AdminEncomendasRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminPromocoesRoute: AdminPromocoesRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminReservasRoute: AdminReservasRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EncomendaConfirmadaOrderIdRoute: EncomendaConfirmadaOrderIdRoute,
  FeedbackIdRoute: FeedbackIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ApiPublicHooksSendFollowupsRoute: ApiPublicHooksSendFollowupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
