/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as DevolucoesInfoRouteImport } from './routes/devolucoes-info'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ColeccaoRouteImport } from './routes/coleccao'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartaoOfertaRouteImport } from './routes/cartao-oferta'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as ArquivoRouteImport } from './routes/arquivo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as FeedbackIdRouteImport } from './routes/feedback.$id'
import { Route as EncomendaConfirmadaOrderIdRouteImport } from './routes/encomenda-confirmada.$orderId'
import { Route as EditorialIdRouteImport } from './routes/editorial_.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminReservasRouteImport } from './routes/admin_.reservas'
import { Route as AdminRelatoriosRouteImport } from './routes/admin_.relatorios'
import { Route as AdminPromocoesRouteImport } from './routes/admin_.promocoes'
import { Route as AdminProdutosRouteImport } from './routes/admin_.produtos'
import { Route as AdminNewsletterRouteImport } from './routes/admin_.newsletter'
import { Route as AdminEncomendasRouteImport } from './routes/admin_.encomendas'
import { Route as AdminEditorialRouteImport } from './routes/admin_.editorial'
import { Route as AdminDevolucoesRouteImport } from './routes/admin_.devolucoes'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin_.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin_.clientes'
import { Route as AdminCartoesOfertaRouteImport } from './routes/admin_.cartoes-oferta'
import { Route as AdminEncomendasIndexRouteImport } from './routes/admin_.encomendas.index'
import { Route as WishlistShareTokenRouteImport } from './routes/wishlist_.share.$token'
import { Route as ColeccaoMarcaSlugRouteImport } from './routes/coleccao.marca.$slug'
import { Route as AdminEncomendasHistoricoRouteImport } from './routes/admin_.encomendas.historico'
import { Route as AdminEncomendasCanceladasRouteImport } from './routes/admin_.encomendas.canceladas'
import { Route as ApiPublicHooksSendFollowupsRouteImport } from './routes/api/public/hooks/send-followups'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucoesInfoRoute = DevolucoesInfoRouteImport.update({
  id: '/devolucoes-info',
  path: '/devolucoes-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccaoRoute = ColeccaoRouteImport.update({
  id: '/coleccao',
  path: '/coleccao',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaoOfertaRoute = CartaoOfertaRouteImport.update({
  id: '/cartao-oferta',
  path: '/cartao-oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivoRoute = ArquivoRouteImport.update({
  id: '/arquivo',
  path: '/arquivo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIdRoute = FeedbackIdRouteImport.update({
  id: '/feedback/$id',
  path: '/feedback/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EncomendaConfirmadaOrderIdRoute =
  EncomendaConfirmadaOrderIdRouteImport.update({
    id: '/encomenda-confirmada/$orderId',
    path: '/encomenda-confirmada/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EditorialIdRoute = EditorialIdRouteImport.update({
  id: '/editorial_/$id',
  path: '/editorial/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/admin_/reservas',
  path: '/admin/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin_/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromocoesRoute = AdminPromocoesRouteImport.update({
  id: '/admin_/promocoes',
  path: '/admin/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin_/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/admin_/newsletter',
  path: '/admin/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEncomendasRoute = AdminEncomendasRouteImport.update({
  id: '/admin_/encomendas',
  path: '/admin/encomendas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorialRoute = AdminEditorialRouteImport.update({
  id: '/admin_/editorial',
  path: '/admin/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevolucoesRoute = AdminDevolucoesRouteImport.update({
  id: '/admin_/devolucoes',
  path: '/admin/devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin_/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin_/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCartoesOfertaRoute = AdminCartoesOfertaRouteImport.update({
  id: '/admin_/cartoes-oferta',
  path: '/admin/cartoes-oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEncomendasIndexRoute = AdminEncomendasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEncomendasRoute,
} as any)
const WishlistShareTokenRoute = WishlistShareTokenRouteImport.update({
  id: '/wishlist_/share/$token',
  path: '/wishlist/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccaoMarcaSlugRoute = ColeccaoMarcaSlugRouteImport.update({
  id: '/marca/$slug',
  path: '/marca/$slug',
  getParentRoute: () => ColeccaoRoute,
} as any)
const AdminEncomendasHistoricoRoute =
  AdminEncomendasHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AdminEncomendasRoute,
  } as any)
const AdminEncomendasCanceladasRoute =
  AdminEncomendasCanceladasRouteImport.update({
    id: '/canceladas',
    path: '/canceladas',
    getParentRoute: () => AdminEncomendasRoute,
  } as any)
const ApiPublicHooksSendFollowupsRoute =
  ApiPublicHooksSendFollowupsRouteImport.update({
    id: '/api/public/hooks/send-followups',
    path: '/api/public/hooks/send-followups',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arquivo': typeof ArquivoRoute
  '/carrinho': typeof CarrinhoRoute
  '/cartao-oferta': typeof CartaoOfertaRoute
  '/checkout': typeof CheckoutRoute
  '/coleccao': typeof ColeccaoRouteWithChildren
  '/contactos': typeof ContactosRoute
  '/devolucoes-info': typeof DevolucoesInfoRoute
  '/editorial': typeof EditorialRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quiz': typeof QuizRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/wishlist': typeof WishlistRoute
  '/admin/cartoes-oferta': typeof AdminCartoesOfertaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/devolucoes': typeof AdminDevolucoesRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/encomendas': typeof AdminEncomendasRouteWithChildren
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/editorial/$id': typeof EditorialIdRoute
  '/encomenda-confirmada/$orderId': typeof EncomendaConfirmadaOrderIdRoute
  '/feedback/$id': typeof FeedbackIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/encomendas/canceladas': typeof AdminEncomendasCanceladasRoute
  '/admin/encomendas/historico': typeof AdminEncomendasHistoricoRoute
  '/coleccao/marca/$slug': typeof ColeccaoMarcaSlugRoute
  '/wishlist/share/$token': typeof WishlistShareTokenRoute
  '/admin/encomendas/': typeof AdminEncomendasIndexRoute
  '/api/public/hooks/send-followups': typeof ApiPublicHooksSendFollowupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arquivo': typeof ArquivoRoute
  '/carrinho': typeof CarrinhoRoute
  '/cartao-oferta': typeof CartaoOfertaRoute
  '/checkout': typeof CheckoutRoute
  '/coleccao': typeof ColeccaoRouteWithChildren
  '/contactos': typeof ContactosRoute
  '/devolucoes-info': typeof DevolucoesInfoRoute
  '/editorial': typeof EditorialRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quiz': typeof QuizRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/wishlist': typeof WishlistRoute
  '/admin/cartoes-oferta': typeof AdminCartoesOfertaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/devolucoes': typeof AdminDevolucoesRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/editorial/$id': typeof EditorialIdRoute
  '/encomenda-confirmada/$orderId': typeof EncomendaConfirmadaOrderIdRoute
  '/feedback/$id': typeof FeedbackIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/encomendas/canceladas': typeof AdminEncomendasCanceladasRoute
  '/admin/encomendas/historico': typeof AdminEncomendasHistoricoRoute
  '/coleccao/marca/$slug': typeof ColeccaoMarcaSlugRoute
  '/wishlist/share/$token': typeof WishlistShareTokenRoute
  '/admin/encomendas': typeof AdminEncomendasIndexRoute
  '/api/public/hooks/send-followups': typeof ApiPublicHooksSendFollowupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arquivo': typeof ArquivoRoute
  '/carrinho': typeof CarrinhoRoute
  '/cartao-oferta': typeof CartaoOfertaRoute
  '/checkout': typeof CheckoutRoute
  '/coleccao': typeof ColeccaoRouteWithChildren
  '/contactos': typeof ContactosRoute
  '/devolucoes-info': typeof DevolucoesInfoRoute
  '/editorial': typeof EditorialRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quiz': typeof QuizRoute
  '/registo': typeof RegistoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/wishlist': typeof WishlistRoute
  '/admin_/cartoes-oferta': typeof AdminCartoesOfertaRoute
  '/admin_/clientes': typeof AdminClientesRoute
  '/admin_/configuracoes': typeof AdminConfiguracoesRoute
  '/admin_/devolucoes': typeof AdminDevolucoesRoute
  '/admin_/editorial': typeof AdminEditorialRoute
  '/admin_/encomendas': typeof AdminEncomendasRouteWithChildren
  '/admin_/newsletter': typeof AdminNewsletterRoute
  '/admin_/produtos': typeof AdminProdutosRoute
  '/admin_/promocoes': typeof AdminPromocoesRoute
  '/admin_/relatorios': typeof AdminRelatoriosRoute
  '/admin_/reservas': typeof AdminReservasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/editorial_/$id': typeof EditorialIdRoute
  '/encomenda-confirmada/$orderId': typeof EncomendaConfirmadaOrderIdRoute
  '/feedback/$id': typeof FeedbackIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin_/encomendas/canceladas': typeof AdminEncomendasCanceladasRoute
  '/admin_/encomendas/historico': typeof AdminEncomendasHistoricoRoute
  '/coleccao/marca/$slug': typeof ColeccaoMarcaSlugRoute
  '/wishlist_/share/$token': typeof WishlistShareTokenRoute
  '/admin_/encomendas/': typeof AdminEncomendasIndexRoute
  '/api/public/hooks/send-followups': typeof ApiPublicHooksSendFollowupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arquivo'
    | '/carrinho'
    | '/cartao-oferta'
    | '/checkout'
    | '/coleccao'
    | '/contactos'
    | '/devolucoes-info'
    | '/editorial'
    | '/experiencias'
    | '/login'
    | '/perfil'
    | '/privacidade'
    | '/quiz'
    | '/registo'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/wishlist'
    | '/admin/cartoes-oferta'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/devolucoes'
    | '/admin/editorial'
    | '/admin/encomendas'
    | '/admin/newsletter'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/admin/relatorios'
    | '/admin/reservas'
    | '/auth/callback'
    | '/editorial/$id'
    | '/encomenda-confirmada/$orderId'
    | '/feedback/$id'
    | '/produto/$id'
    | '/admin/encomendas/canceladas'
    | '/admin/encomendas/historico'
    | '/coleccao/marca/$slug'
    | '/wishlist/share/$token'
    | '/admin/encomendas/'
    | '/api/public/hooks/send-followups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arquivo'
    | '/carrinho'
    | '/cartao-oferta'
    | '/checkout'
    | '/coleccao'
    | '/contactos'
    | '/devolucoes-info'
    | '/editorial'
    | '/experiencias'
    | '/login'
    | '/perfil'
    | '/privacidade'
    | '/quiz'
    | '/registo'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/wishlist'
    | '/admin/cartoes-oferta'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/devolucoes'
    | '/admin/editorial'
    | '/admin/newsletter'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/admin/relatorios'
    | '/admin/reservas'
    | '/auth/callback'
    | '/editorial/$id'
    | '/encomenda-confirmada/$orderId'
    | '/feedback/$id'
    | '/produto/$id'
    | '/admin/encomendas/canceladas'
    | '/admin/encomendas/historico'
    | '/coleccao/marca/$slug'
    | '/wishlist/share/$token'
    | '/admin/encomendas'
    | '/api/public/hooks/send-followups'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arquivo'
    | '/carrinho'
    | '/cartao-oferta'
    | '/checkout'
    | '/coleccao'
    | '/contactos'
    | '/devolucoes-info'
    | '/editorial'
    | '/experiencias'
    | '/login'
    | '/perfil'
    | '/privacidade'
    | '/quiz'
    | '/registo'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/wishlist'
    | '/admin_/cartoes-oferta'
    | '/admin_/clientes'
    | '/admin_/configuracoes'
    | '/admin_/devolucoes'
    | '/admin_/editorial'
    | '/admin_/encomendas'
    | '/admin_/newsletter'
    | '/admin_/produtos'
    | '/admin_/promocoes'
    | '/admin_/relatorios'
    | '/admin_/reservas'
    | '/auth/callback'
    | '/editorial_/$id'
    | '/encomenda-confirmada/$orderId'
    | '/feedback/$id'
    | '/produto/$id'
    | '/admin_/encomendas/canceladas'
    | '/admin_/encomendas/historico'
    | '/coleccao/marca/$slug'
    | '/wishlist_/share/$token'
    | '/admin_/encomendas/'
    | '/api/public/hooks/send-followups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArquivoRoute: typeof ArquivoRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CartaoOfertaRoute: typeof CartaoOfertaRoute
  CheckoutRoute: typeof CheckoutRoute
  ColeccaoRoute: typeof ColeccaoRouteWithChildren
  ContactosRoute: typeof ContactosRoute
  DevolucoesInfoRoute: typeof DevolucoesInfoRoute
  EditorialRoute: typeof EditorialRoute
  ExperienciasRoute: typeof ExperienciasRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  QuizRoute: typeof QuizRoute
  RegistoRoute: typeof RegistoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  WishlistRoute: typeof WishlistRoute
  AdminCartoesOfertaRoute: typeof AdminCartoesOfertaRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDevolucoesRoute: typeof AdminDevolucoesRoute
  AdminEditorialRoute: typeof AdminEditorialRoute
  AdminEncomendasRoute: typeof AdminEncomendasRouteWithChildren
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminPromocoesRoute: typeof AdminPromocoesRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EditorialIdRoute: typeof EditorialIdRoute
  EncomendaConfirmadaOrderIdRoute: typeof EncomendaConfirmadaOrderIdRoute
  FeedbackIdRoute: typeof FeedbackIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  WishlistShareTokenRoute: typeof WishlistShareTokenRoute
  ApiPublicHooksSendFollowupsRoute: typeof ApiPublicHooksSendFollowupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devolucoes-info': {
      id: '/devolucoes-info'
      path: '/devolucoes-info'
      fullPath: '/devolucoes-info'
      preLoaderRoute: typeof DevolucoesInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccao': {
      id: '/coleccao'
      path: '/coleccao'
      fullPath: '/coleccao'
      preLoaderRoute: typeof ColeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartao-oferta': {
      id: '/cartao-oferta'
      path: '/cartao-oferta'
      fullPath: '/cartao-oferta'
      preLoaderRoute: typeof CartaoOfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivo': {
      id: '/arquivo'
      path: '/arquivo'
      fullPath: '/arquivo'
      preLoaderRoute: typeof ArquivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$id': {
      id: '/feedback/$id'
      path: '/feedback/$id'
      fullPath: '/feedback/$id'
      preLoaderRoute: typeof FeedbackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encomenda-confirmada/$orderId': {
      id: '/encomenda-confirmada/$orderId'
      path: '/encomenda-confirmada/$orderId'
      fullPath: '/encomenda-confirmada/$orderId'
      preLoaderRoute: typeof EncomendaConfirmadaOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial_/$id': {
      id: '/editorial_/$id'
      path: '/editorial/$id'
      fullPath: '/editorial/$id'
      preLoaderRoute: typeof EditorialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reservas': {
      id: '/admin_/reservas'
      path: '/admin/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/relatorios': {
      id: '/admin_/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/promocoes': {
      id: '/admin_/promocoes'
      path: '/admin/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AdminPromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/produtos': {
      id: '/admin_/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/newsletter': {
      id: '/admin_/newsletter'
      path: '/admin/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/encomendas': {
      id: '/admin_/encomendas'
      path: '/admin/encomendas'
      fullPath: '/admin/encomendas'
      preLoaderRoute: typeof AdminEncomendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/editorial': {
      id: '/admin_/editorial'
      path: '/admin/editorial'
      fullPath: '/admin/editorial'
      preLoaderRoute: typeof AdminEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/devolucoes': {
      id: '/admin_/devolucoes'
      path: '/admin/devolucoes'
      fullPath: '/admin/devolucoes'
      preLoaderRoute: typeof AdminDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/configuracoes': {
      id: '/admin_/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/clientes': {
      id: '/admin_/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cartoes-oferta': {
      id: '/admin_/cartoes-oferta'
      path: '/admin/cartoes-oferta'
      fullPath: '/admin/cartoes-oferta'
      preLoaderRoute: typeof AdminCartoesOfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/encomendas/': {
      id: '/admin_/encomendas/'
      path: '/'
      fullPath: '/admin/encomendas/'
      preLoaderRoute: typeof AdminEncomendasIndexRouteImport
      parentRoute: typeof AdminEncomendasRoute
    }
    '/wishlist_/share/$token': {
      id: '/wishlist_/share/$token'
      path: '/wishlist/share/$token'
      fullPath: '/wishlist/share/$token'
      preLoaderRoute: typeof WishlistShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccao/marca/$slug': {
      id: '/coleccao/marca/$slug'
      path: '/marca/$slug'
      fullPath: '/coleccao/marca/$slug'
      preLoaderRoute: typeof ColeccaoMarcaSlugRouteImport
      parentRoute: typeof ColeccaoRoute
    }
    '/admin_/encomendas/historico': {
      id: '/admin_/encomendas/historico'
      path: '/historico'
      fullPath: '/admin/encomendas/historico'
      preLoaderRoute: typeof AdminEncomendasHistoricoRouteImport
      parentRoute: typeof AdminEncomendasRoute
    }
    '/admin_/encomendas/canceladas': {
      id: '/admin_/encomendas/canceladas'
      path: '/canceladas'
      fullPath: '/admin/encomendas/canceladas'
      preLoaderRoute: typeof AdminEncomendasCanceladasRouteImport
      parentRoute: typeof AdminEncomendasRoute
    }
    '/api/public/hooks/send-followups': {
      id: '/api/public/hooks/send-followups'
      path: '/api/public/hooks/send-followups'
      fullPath: '/api/public/hooks/send-followups'
      preLoaderRoute: typeof ApiPublicHooksSendFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ColeccaoRouteChildren {
  ColeccaoMarcaSlugRoute: typeof ColeccaoMarcaSlugRoute
}

const ColeccaoRouteChildren: ColeccaoRouteChildren = {
  ColeccaoMarcaSlugRoute: ColeccaoMarcaSlugRoute,
}

const ColeccaoRouteWithChildren = ColeccaoRoute._addFileChildren(
  ColeccaoRouteChildren,
)

interface AdminEncomendasRouteChildren {
  AdminEncomendasCanceladasRoute: typeof AdminEncomendasCanceladasRoute
  AdminEncomendasHistoricoRoute: typeof AdminEncomendasHistoricoRoute
  AdminEncomendasIndexRoute: typeof AdminEncomendasIndexRoute
}

const AdminEncomendasRouteChildren: AdminEncomendasRouteChildren = {
  AdminEncomendasCanceladasRoute: AdminEncomendasCanceladasRoute,
  AdminEncomendasHistoricoRoute: AdminEncomendasHistoricoRoute,
  AdminEncomendasIndexRoute: AdminEncomendasIndexRoute,
}

const AdminEncomendasRouteWithChildren = AdminEncomendasRoute._addFileChildren(
  AdminEncomendasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArquivoRoute: ArquivoRoute,
  CarrinhoRoute: CarrinhoRoute,
  CartaoOfertaRoute: CartaoOfertaRoute,
  CheckoutRoute: CheckoutRoute,
  ColeccaoRoute: ColeccaoRouteWithChildren,
  ContactosRoute: ContactosRoute,
  DevolucoesInfoRoute: DevolucoesInfoRoute,
  EditorialRoute: EditorialRoute,
  ExperienciasRoute: ExperienciasRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  QuizRoute: QuizRoute,
  RegistoRoute: RegistoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  WishlistRoute: WishlistRoute,
  AdminCartoesOfertaRoute: AdminCartoesOfertaRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDevolucoesRoute: AdminDevolucoesRoute,
  AdminEditorialRoute: AdminEditorialRoute,
  AdminEncomendasRoute: AdminEncomendasRouteWithChildren,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminPromocoesRoute: AdminPromocoesRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminReservasRoute: AdminReservasRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EditorialIdRoute: EditorialIdRoute,
  EncomendaConfirmadaOrderIdRoute: EncomendaConfirmadaOrderIdRoute,
  FeedbackIdRoute: FeedbackIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  WishlistShareTokenRoute: WishlistShareTokenRoute,
  ApiPublicHooksSendFollowupsRoute: ApiPublicHooksSendFollowupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
